// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureVotingSystem.Infrastructure.Data;

#nullable disable

namespace SecureVotingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250727141245_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SecureVotingSystem.Core.Models.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVoted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivationCode")
                        .IsUnique();

                    b.ToTable("Voters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = "VOTE001",
                            Created = new DateTime(2025, 7, 27, 14, 12, 43, 545, DateTimeKind.Utc).AddTicks(5051),
                            FullName = "Alice Smith",
                            IsVoted = false,
                            Modified = new DateTime(2025, 7, 27, 14, 12, 43, 545, DateTimeKind.Utc).AddTicks(5234),
                            PhoneNumber = "111-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            ActivationCode = "VOTE002",
                            Created = new DateTime(2025, 7, 27, 14, 12, 43, 545, DateTimeKind.Utc).AddTicks(5393),
                            FullName = "Bob Johnson",
                            IsVoted = false,
                            Modified = new DateTime(2025, 7, 27, 14, 12, 43, 545, DateTimeKind.Utc).AddTicks(5393),
                            PhoneNumber = "444-555-6666"
                        },
                        new
                        {
                            Id = 3,
                            ActivationCode = "VOTE003",
                            Created = new DateTime(2025, 7, 27, 14, 12, 43, 545, DateTimeKind.Utc).AddTicks(5395),
                            FullName = "Charlie Brown",
                            IsVoted = true,
                            Modified = new DateTime(2025, 7, 27, 14, 12, 43, 545, DateTimeKind.Utc).AddTicks(5395),
                            PhoneNumber = "777-888-9999"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
