// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureVotingSystem.Infrastructure.Data;

#nullable disable

namespace SecureVotingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250727175033_CandidateAndVote")]
    partial class CandidateAndVote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SecureVotingSystem.Core.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Created = new DateTime(2025, 7, 27, 17, 50, 32, 936, DateTimeKind.Utc).AddTicks(334),
                            Modified = new DateTime(2025, 7, 27, 17, 50, 32, 936, DateTimeKind.Utc).AddTicks(514),
                            Name = "Candidate A"
                        },
                        new
                        {
                            Id = 102,
                            Created = new DateTime(2025, 7, 27, 17, 50, 32, 936, DateTimeKind.Utc).AddTicks(668),
                            Modified = new DateTime(2025, 7, 27, 17, 50, 32, 936, DateTimeKind.Utc).AddTicks(669),
                            Name = "Candidate B"
                        },
                        new
                        {
                            Id = 103,
                            Created = new DateTime(2025, 7, 27, 17, 50, 32, 936, DateTimeKind.Utc).AddTicks(670),
                            Modified = new DateTime(2025, 7, 27, 17, 50, 32, 936, DateTimeKind.Utc).AddTicks(671),
                            Name = "Candidate C"
                        });
                });

            modelBuilder.Entity("SecureVotingSystem.Core.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VoteTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("VoterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("VoterId")
                        .IsUnique();

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateId = 101,
                            VoteTimestamp = new DateTime(2025, 7, 27, 17, 40, 32, 939, DateTimeKind.Utc).AddTicks(5406),
                            VoterId = 1
                        },
                        new
                        {
                            Id = 2,
                            CandidateId = 102,
                            VoteTimestamp = new DateTime(2025, 7, 27, 17, 45, 32, 939, DateTimeKind.Utc).AddTicks(5682),
                            VoterId = 2
                        });
                });

            modelBuilder.Entity("SecureVotingSystem.Core.Models.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVoted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivationCode")
                        .IsUnique();

                    b.ToTable("Voters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = "VOTE001",
                            Created = new DateTime(2025, 7, 27, 17, 50, 32, 935, DateTimeKind.Utc).AddTicks(1844),
                            FullName = "Alice Smith",
                            IsVoted = false,
                            Modified = new DateTime(2025, 7, 27, 17, 50, 32, 935, DateTimeKind.Utc).AddTicks(2022),
                            PhoneNumber = "111-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            ActivationCode = "VOTE002",
                            Created = new DateTime(2025, 7, 27, 17, 50, 32, 935, DateTimeKind.Utc).AddTicks(2175),
                            FullName = "Bob Johnson",
                            IsVoted = false,
                            Modified = new DateTime(2025, 7, 27, 17, 50, 32, 935, DateTimeKind.Utc).AddTicks(2175),
                            PhoneNumber = "444-555-6666"
                        },
                        new
                        {
                            Id = 3,
                            ActivationCode = "VOTE003",
                            Created = new DateTime(2025, 7, 27, 17, 50, 32, 935, DateTimeKind.Utc).AddTicks(2177),
                            FullName = "Charlie Brown",
                            IsVoted = true,
                            Modified = new DateTime(2025, 7, 27, 17, 50, 32, 935, DateTimeKind.Utc).AddTicks(2178),
                            PhoneNumber = "777-888-9999"
                        });
                });

            modelBuilder.Entity("SecureVotingSystem.Core.Models.Vote", b =>
                {
                    b.HasOne("SecureVotingSystem.Core.Models.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecureVotingSystem.Core.Models.Voter", "Voter")
                        .WithMany("Votes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("SecureVotingSystem.Core.Models.Candidate", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SecureVotingSystem.Core.Models.Voter", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
